server:
  port: 8083
  error:
    whitelabel:
      enabled: true
logging:
  level:
    org.springframework.web: ERROR
    org.springframework.data: ERROR
    
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: trace.log
spring:
    profiles:
        active: prod
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate
            dialect: org.hibernate.dialect.MySQL5Dialect

#    datasource:
#        url: jdbc:mysql://localhost:3308/lifantou?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#        username: root
#        password:
#        driver-class-name: com.mysql.cj.jdbc.Driver

    datasource:
        url: jdbc:mysql://localhost/lifantou?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
        username: root
        password: Digit@l2019
        driver-class-name: com.mysql.cj.jdbc.Driver

    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: lifantou.workgroup@gmail.com
        password: 783001198@
        protocol: smtp
        tls: true
        properties.mail.smtp:
              auth: true
              starttls.enable: true
              ssl.trust: smtp.gmail.com